apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
 name: backstage-local
 description: An example of a Backstage application.
 # Example for optional annotations
 # annotations:
 #   github.com/project-slug: backstage/backstage
 #   backstage.io/techdocs-ref: dir:.
spec:
 type: website
 owner: john@example.com
 lifecycle: experimental

#apiVersion: backstage.io/v1alpha1
#kind: Component
#metadata:
#  name: plugin-argocd-autopilot
#spec:
#  lifecycle: production
#  owner: my-team
#  type: service
#---
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   annotations:
#     argocd/app-selector: "app.kubernetes.io/managed-by=argocd-autopilot"
#   name: argocd-autopilot
# spec:
#   lifecycle: production
#   owner: my-team
#   type: service
#
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: gcp-folder
# spec:
#   lifecycle: production
#   owner: mirage-team
#   type: service
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: datasci-project
# spec:
#   lifecycle: produciton
#   owner: data
#   type: service

