
steps:
# - name: node:14
#   entrypoint: "bash"
#   args:
#   - '-c'
#   - |
#     yarn install; yarn add --cwd packages/backend; cd packages/backend; yarn backstage-cli package build --role backend

- name: "gcr.io/kaniko-project/executor:latest"
  args:
    - --destination=us.gcr.io/px-test1-project-ici/px-backstage:$COMMIT_SHA
    - --destination=us.gcr.io/px-test1-project-ici/px-backstage:latest
    - --dockerfile=./Dockerfile
    - --context=.
    - --cache=true
    - --cache-ttl=240h

# - name: "gcr.io/walker-cpl/helm"
#   id: Helm-Upgrade
#   entrypoint: "bash"
#   args:
#     - "c"
#     - |
#       helm template backstage-dev ./charts -n backstage-dev -f ./
# - name: "gcr.io/px-mike-project-hje/cloud-builders-helm"
#   entrypoint: "bash"
#   args: 
#     - '-c'
#     - |
#       helm template backstage ./manifests/backstage -n backstage -f ./manifests/values.yaml
#       helm upgrade -i backstage ./manifests/backstage -n backstage

timeout: 1200s
options:
  machineType: E2_HIGHCPU_32

