
steps:
- name: "gcr.io/kaniko-project/executor:latest"
  args:
    - --destination=us.gcr.io/px-test1-project-ici/mayo-backstage:$COMMIT_SHA
    - --destination=us.gcr.io/px-test1-project-ici/mayo-backstage:latest
    - --dockerfile=./Dockerfile
    - --context=.
    - --cache=true
    - --cache-ttl=240h

timeout: 1200s
options:
  machineType: E2_HIGHCPU_32

